/* 
 * My API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing CompleteTenantEvictionInfo
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class CompleteTenantEvictionInfoTests
    {
        // TODO uncomment below to declare an instance variable for CompleteTenantEvictionInfo
        //private CompleteTenantEvictionInfo instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of CompleteTenantEvictionInfo
            //instance = new CompleteTenantEvictionInfo();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of CompleteTenantEvictionInfo
        /// </summary>
        [Test]
        public void CompleteTenantEvictionInfoInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" CompleteTenantEvictionInfo
            //Assert.IsInstanceOfType<CompleteTenantEvictionInfo> (instance, "variable 'instance' is a CompleteTenantEvictionInfo");
        }


        /// <summary>
        /// Test the property 'TenantInfo'
        /// </summary>
        [Test]
        public void TenantInfoTest()
        {
            // TODO unit test for the property 'TenantInfo'
        }
        /// <summary>
        /// Test the property 'AddressInfo'
        /// </summary>
        [Test]
        public void AddressInfoTest()
        {
            // TODO unit test for the property 'AddressInfo'
        }
        /// <summary>
        /// Test the property 'EvictionInfo'
        /// </summary>
        [Test]
        public void EvictionInfoTest()
        {
            // TODO unit test for the property 'EvictionInfo'
        }

    }

}
