/* 
 * My API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing EvictionInfo
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class EvictionInfoTests
    {
        // TODO uncomment below to declare an instance variable for EvictionInfo
        //private EvictionInfo instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of EvictionInfo
            //instance = new EvictionInfo();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of EvictionInfo
        /// </summary>
        [Test]
        public void EvictionInfoInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" EvictionInfo
            //Assert.IsInstanceOfType<EvictionInfo> (instance, "variable 'instance' is a EvictionInfo");
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'DateOfEviction'
        /// </summary>
        [Test]
        public void DateOfEvictionTest()
        {
            // TODO unit test for the property 'DateOfEviction'
        }

    }

}
