/* 
 * My API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using IO.Swagger.Client;
using IO.Swagger.Api;
using IO.Swagger.Model;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing AddressApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class AddressApiTests
    {
        private AddressApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new AddressApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of AddressApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' AddressApi
            //Assert.IsInstanceOfType(typeof(AddressApi), instance, "instance is a AddressApi");
        }

        /// <summary>
        /// Test ApiAddressGet
        /// </summary>
        [Test]
        public void ApiAddressGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.ApiAddressGet();
            //Assert.IsInstanceOf<List<string>> (response, "response is List<string>");
        }
        /// <summary>
        /// Test ApiAddressIdDelete
        /// </summary>
        [Test]
        public void ApiAddressIdDeleteTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int? id = null;
            //instance.ApiAddressIdDelete(id);
            
        }
        /// <summary>
        /// Test ApiAddressIdGet
        /// </summary>
        [Test]
        public void ApiAddressIdGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string id = null;
            //int? addressId = null;
            //var response = instance.ApiAddressIdGet(id, addressId);
            //Assert.IsInstanceOf<AddressInfo> (response, "response is AddressInfo");
        }
        /// <summary>
        /// Test ApiAddressIdPut
        /// </summary>
        [Test]
        public void ApiAddressIdPutTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int? id = null;
            //string body = null;
            //instance.ApiAddressIdPut(id, body);
            
        }
        /// <summary>
        /// Test ApiAddressPost
        /// </summary>
        [Test]
        public void ApiAddressPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //AddressInfo body = null;
            //instance.ApiAddressPost(body);
            
        }
    }

}
