/* 
 * My API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using IO.Swagger.Client;
using IO.Swagger.Api;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing EvictionApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class EvictionApiTests
    {
        private EvictionApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new EvictionApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of EvictionApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' EvictionApi
            //Assert.IsInstanceOfType(typeof(EvictionApi), instance, "instance is a EvictionApi");
        }

        /// <summary>
        /// Test ApiEvictionGet
        /// </summary>
        [Test]
        public void ApiEvictionGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.ApiEvictionGet();
            //Assert.IsInstanceOf<List<string>> (response, "response is List<string>");
        }
        /// <summary>
        /// Test ApiEvictionIdDelete
        /// </summary>
        [Test]
        public void ApiEvictionIdDeleteTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int? id = null;
            //instance.ApiEvictionIdDelete(id);
            
        }
        /// <summary>
        /// Test ApiEvictionIdGet
        /// </summary>
        [Test]
        public void ApiEvictionIdGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int? id = null;
            //var response = instance.ApiEvictionIdGet(id);
            //Assert.IsInstanceOf<string> (response, "response is string");
        }
        /// <summary>
        /// Test ApiEvictionIdPut
        /// </summary>
        [Test]
        public void ApiEvictionIdPutTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int? id = null;
            //string body = null;
            //instance.ApiEvictionIdPut(id, body);
            
        }
        /// <summary>
        /// Test ApiEvictionPost
        /// </summary>
        [Test]
        public void ApiEvictionPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string body = null;
            //instance.ApiEvictionPost(body);
            
        }
    }

}
