/* 
 * My API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using IO.Swagger.Client;
using IO.Swagger.Api;
using IO.Swagger.Model;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing TenantApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class TenantApiTests
    {
        private TenantApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new TenantApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of TenantApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' TenantApi
            //Assert.IsInstanceOfType(typeof(TenantApi), instance, "instance is a TenantApi");
        }

        /// <summary>
        /// Test ApiTenantGet
        /// </summary>
        [Test]
        public void ApiTenantGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.ApiTenantGet();
            //Assert.IsInstanceOf<List<string>> (response, "response is List<string>");
        }
        /// <summary>
        /// Test ApiTenantIdDelete
        /// </summary>
        [Test]
        public void ApiTenantIdDeleteTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int? id = null;
            //instance.ApiTenantIdDelete(id);
            
        }
        /// <summary>
        /// Test ApiTenantIdGet
        /// </summary>
        [Test]
        public void ApiTenantIdGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int? id = null;
            //var response = instance.ApiTenantIdGet(id);
            //Assert.IsInstanceOf<TenantInfo> (response, "response is TenantInfo");
        }
        /// <summary>
        /// Test ApiTenantIdPut
        /// </summary>
        [Test]
        public void ApiTenantIdPutTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int? id = null;
            //string body = null;
            //instance.ApiTenantIdPut(id, body);
            
        }
        /// <summary>
        /// Test ApiTenantPost
        /// </summary>
        [Test]
        public void ApiTenantPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //CompleteTenantEvictionInfo body = null;
            //instance.ApiTenantPost(body);
            
        }
    }

}
